name: CD - Deploy to EC2

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH key
      run: |
        echo "${{ secrets.EC2_SSH_KEY }}" > key.pem
        chmod 400 key.pem

    - name: Deploy to EC2
      run: |
        ssh -o StrictHostKeyChecking=no -i key.pem ec2-user@${{ secrets.EC2_HOST }} << 'EOF'
          docker stop $(docker ps -q)
          docker pull samir3112/contact-api
          docker run -d -p 80:5000 \
            -e DB_USER=admin \
            -e DB_PASS=password123 \
            -e DB_HOST=${{ secrets.RDS_ENDPOINT }} \
            -e DB_NAME=contactdb \
            samir3112/contact-api
        EOF
